# Generated by Django 3.2.2 on 2022-05-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MEDICAMENTO',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de medicamento')),
                ('nombre_medicamento', models.CharField(max_length=50, verbose_name='Nombre del medicamento')),
                ('precio_medicamento', models.IntegerField(max_length=8, verbose_name='Precio del medicamento')),
                ('stock_medicamento', models.IntegerField(max_length=6, verbose_name='Stock del medicamento')),
                ('estado_medicamento', models.CharField(max_length=12, verbose_name='Estado del medicamento')),
                ('gramos_medicamento', models.IntegerField(max_length=4, verbose_name='Gramos del medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('rut_pac', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut (sin punto ni guión) del paciente')),
                ('nombre_pac', models.CharField(max_length=50, verbose_name='Nombre del paciente')),
                ('correo_pac', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('numero_pac', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='TUTOR',
            fields=[
                ('rut_tutor', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut (sin punto ni guión) del paciente')),
                ('nombre_tutor', models.CharField(max_length=50, verbose_name='Nombre del paciente')),
                ('correo_tutor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('numero_tutor', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_TIPO_USU', models.CharField(max_length=50, verbose_name='Nombre del tipo de usuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRESCRIPCION',
            fields=[
                ('id_prescripcion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la prescripcion')),
                ('desc_prescripcion', models.CharField(max_length=9999, verbose_name='Descripcion de la prescripcion')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de emision')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
                ('nombre_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CesfamApp.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CesfamApp.tutor', verbose_name='Tutor'),
        ),
    ]
